INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (11, 'Rodônia','RO');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (12, 'Acre','AC');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (13, 'Amazonas','AM');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (14, 'Roraima','RR');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (15, 'Pará','PA');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (16, 'Amapá','AP');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (17, 'Tocantins','TO');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (21, 'Maranhão','MA');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (22, 'Piauí','PI');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (23, 'Ceará','CE');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (24, 'Rio Grande do Norte','RN');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (25, 'Paraíba','PB');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (26, 'Pernambuco','PE');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (27, 'Alagoas','AL');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (28, 'Sergipe','SE');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (29, 'Bahia','BA');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (31, 'Minas Gerais','MG');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (32, 'Espírito Santo','ES');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (33, 'Rio de Janeiro','RJ');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (35, 'São Paulo','SP');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (41, 'Paraná','PR');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (42, 'Santa Catarina','SC');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (43, 'Rio Grande do Sul','RS');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (50, 'Mato Grosso do Sul','MS');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (51, 'Mato Grosso','MT');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (52, 'Goias','GO');
INSERT INTO UND_FDRL(cd_und_fdrl,nm_und_fdrl,sg_und_fdrl) VALUES (53, 'Distrito Federal','DF'); 
